# Generated by Django 4.1.7 on 2023-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_jobapplication_status_job_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='car_documents',
            field=models.ImageField(default='docs/default_car.jpg', upload_to='job/car', verbose_name='Фото техпаспорту'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='insurance',
            field=models.ImageField(default='docs/default_insurance.png', upload_to='job/insurance', verbose_name='Автоцивілка'),
        ),
    ]
