# Generated by Django 4.1.7 on 2023-03-31 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reportuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseOfCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_vehicle', models.CharField(max_length=255, verbose_name='Користувач автомобіля')),
                ('chat_id', models.CharField(blank=True, max_length=100, verbose_name='Індетифікатор чата')),
                ('licence_plate', models.CharField(max_length=24, verbose_name='Номерний знак')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Початок використання авто')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Кінець використання авто')),
            ],
            options={
                'verbose_name': 'Користувачі автомобіля',
                'verbose_name_plural': 'Користувачі автомобілів',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва статусу')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='RentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=50)),
                ('rent_time', models.DurationField(blank=True, null=True, verbose_name='Час оренди')),
                ('rent_distance', models.FloatField(blank=True, null=True, verbose_name='Орендована дистанція')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver')),
            ],
        ),
    ]
