# Generated by Django 4.1.7 on 2023-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_jobapplication_status_job_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuklonfleet',
            name='token',
            field=models.CharField(default=None, max_length=40, verbose_name='Код автопарку'),
        ),
    ]
