# Generated by Django 4.1.7 on 2023-04-02 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_jobapplication_status_job_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, max_length=50)),
                ('rent_time', models.DurationField(blank=True, null=True, verbose_name='Час оренди')),
                ('rent_distance', models.FloatField(blank=True, null=True, verbose_name='Орендована дистанція')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='useofcars',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Кінець використання авто'),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва статусу')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driver')),
            ],
        ),
    ]
