# Generated by Django 4.1 on 2023-04-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_car_delivery_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentinformation',
            options={'verbose_name_plural': 'Інформація по оренді'},
        ),
    ]
