# Generated by Django 4.1 on 2023-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_parksettings_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentinformation',
            options={'verbose_name_plural': 'Інформація по оренді'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID в чаті'),
        ),
        migrations.AlterField(
            model_name='event',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='chat_id_client',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='useofcars',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата'),
        ),
    ]
