# Generated by Django 4.1 on 2023-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_rentinformation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='parksettings',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Опиc'),
        ),
    ]
