# Generated by Django 4.1 on 2023-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_order_checked_alter_order_car_delivery_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file_name', models.CharField(max_length=255)),
                ('driver_external_id', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10)),
                ('start_trip', models.DateTimeField(blank=True, null=True)),
                ('end_trip', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
