# Generated by Django 4.1 on 2023-06-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_park_partner_ubertrips_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_report', models.DateTimeField(verbose_name='Звіт з')),
                ('end_report', models.DateTimeField(verbose_name='Звіт по')),
                ('driver', models.CharField(max_length=25, null=True, verbose_name='Водій авто')),
                ('efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Ефективність грн/км')),
            ],
            options={
                'verbose_name': 'Ефективність автомобіля',
                'verbose_name_plural': 'Ефективність автомобілів',
            },
        ),
    ]
