# Generated by Django 4.1 on 2023-06-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_boltpaymentsorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='boltpaymentsorder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='drivermanager',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='newuklonpaymentsorder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='ninjapaymentsorder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='rentinformation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='uberpaymentsorder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер'),
        ),
    ]
