# Generated by Django 4.1 on 2023-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_carefficiency_remove_client_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gps_id',
            field=models.IntegerField(default=0),
        ),
    ]
