# Generated by Django 4.1 on 2023-06-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_comment_partner_alter_boltpaymentsorder_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermanager',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='driver',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.drivermanager', verbose_name='Менеджер водіїв'),
        ),
    ]
