# Generated by Django 4.1 on 2023-07-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_park_options_vehicle_gps_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_from', models.DateTimeField(verbose_name='Репорт з')),
                ('report_to', models.DateTimeField(verbose_name='Репорт по')),
                ('vendor_name', models.CharField(default='Ninja', max_length=30, verbose_name='Агрегатор')),
                ('full_name', models.CharField(max_length=255, null=True, verbose_name='ПІ водія')),
                ('driver_id', models.CharField(max_length=50, null=True, verbose_name='Унікальний індифікатор водія')),
                ('total_rides', models.PositiveIntegerField(null=True, verbose_name='Кількість поїздок')),
                ('total_distance', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Пробіг під замовлення')),
                ('total_amount_cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Готівкою')),
                ('total_amount_on_card', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='На картку')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Загальна сума')),
                ('tips', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Чайові')),
                ('bonuses', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Бонуси')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Комісія')),
                ('total_amount_without_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Чистий дохід')),
                ('fares', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Штрафи')),
                ('cancels', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Плата за скасування')),
                ('compensations', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Компенсації')),
                ('refunds', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Повернення коштів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.partner', verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Звіт',
                'verbose_name_plural': 'Звіти',
                'unique_together': {('report_from', 'report_to', 'driver_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='boltpaymentsorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='boltpaymentsorder',
            name='partner',
        ),
        migrations.AlterUniqueTogether(
            name='newuklonpaymentsorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='newuklonpaymentsorder',
            name='partner',
        ),
        migrations.AlterUniqueTogether(
            name='ninjapaymentsorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ninjapaymentsorder',
            name='partner',
        ),
        migrations.DeleteModel(
            name='PaymentsOrder',
        ),
        migrations.AlterUniqueTogether(
            name='uberpaymentsorder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uberpaymentsorder',
            name='partner',
        ),
        migrations.DeleteModel(
            name='UklonPaymentsOrder',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='chat_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Індетифікатор чата'),
        ),
        migrations.DeleteModel(
            name='BoltPaymentsOrder',
        ),
        migrations.DeleteModel(
            name='NewUklonPaymentsOrder',
        ),
        migrations.DeleteModel(
            name='NinjaPaymentsOrder',
        ),
        migrations.DeleteModel(
            name='UberPaymentsOrder',
        ),
    ]
