# Generated by Django 4.1 on 2023-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_park_options_vehicle_gps_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Інформаційна панель автопарку',
                'verbose_name_plural': 'Інформаційна панель автопарку',
            },
        ),
        migrations.AddField(
            model_name='carefficiency',
            name='vehicle',
            field=models.CharField(max_length=255, null=True, verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='carefficiency',
            name='driver',
            field=models.CharField(max_length=50, null=True, verbose_name='Водій авто'),
        ),
    ]
