# Generated by Django 4.1 on 2023-07-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_park_options_vehicle_gps_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Інформаційна панель автопарку',
                'verbose_name_plural': 'Інформаційна панель автопарку',
            },
        ),
    ]
