# Generated by Django 4.1 on 2023-08-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_useofcars_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Відпочинок і лікування', 'verbose_name_plural': 'Відпочинки і лікування'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час події'),
        ),
    ]
