# Generated by Django 4.1 on 2023-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_event_options_remove_event_status_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info',
            field=models.CharField(max_length=255, null=True, verbose_name='Додаткова інформація'),
        ),
    ]
