# Generated by Django 4.1 on 2023-08-17 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0041_remove_carefficiency_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електрона пошта'),
        ),
        migrations.AddField(
            model_name='partner',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я")),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Прізвище')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електрона пошта')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона')),
                ('chat_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Індетифікатор чата')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнер')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджери',
            },
        ),
        migrations.AlterField(
            model_name='driver',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.manager', verbose_name='Менеджер водіїв'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.manager', verbose_name='Менеджер авто'),
        ),
        migrations.DeleteModel(
            name='DriverManager',
        ),
    ]
