# Generated by Django 4.1 on 2023-08-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_vehicle_investor_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_message_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver_message_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_hours',
            field=models.IntegerField(null=True, verbose_name='Годин Сплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(default='Звичайне замовлення', max_length=100, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='fleets_drivers_vehicles_rate',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehicle', verbose_name='Автомобіль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=70, null=True, verbose_name='Спосіб оплати'),
        ),
    ]
