# Generated by Django 4.1 on 2023-08-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_vehicle_investor_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='report_tg',
        ),
        migrations.AddField(
            model_name='reporttelegrampayments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Замовлення'),
        ),
    ]
