# Generated by Django 4.1 on 2023-09-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_transactionsconversantion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Логін'),
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль'),
        ),
    ]
