# Generated by Django 4.1 on 2023-09-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_transactionsconversantion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_message_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver_message_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_hours',
            field=models.IntegerField(null=True, verbose_name='Годин Сплачено'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(default='Звичайне замовлення', max_length=100, verbose_name='Тип замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(max_length=70, null=True, verbose_name='Спосіб оплати'),
        ),
    ]
