# Generated by Django 4.1 on 2023-08-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_transactionsconversantion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='report_tg',
        ),
        migrations.AddField(
            model_name='driver',
            name='worked',
            field=models.BooleanField(default=True, verbose_name='Працює'),
        ),
        migrations.AddField(
            model_name='reporttelegrampayments',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Замовлення'),
        ),
    ]
