# Generated by Django 4.1 on 2023-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_order_client_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='fleet',
        ),
        migrations.RemoveField(
            model_name='fleets_drivers_vehicles_rate',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='fleetorder',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Відстань за маршрутом'),
        ),
    ]
