# Generated by Django 4.1 on 2023-09-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_remove_order_client_message_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='fleet',
        ),
        migrations.RemoveField(
            model_name='fleets_drivers_vehicles_rate',
            name='vehicle',
        ),
    ]
