# Generated by Django 4.1 on 2023-09-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_vehiclespending_delete_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chat_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Група автомобіля'),
        ),
    ]
