# Generated by Django 4.1 on 2023-11-09 08:22

from django.db import migrations, models
import django.db.models.deletion
import selenium_ninja.driver
import selenium_ninja.synchronizer


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_subscribeusers_name_subscribeusers_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UaGpsSynchronizer',
            fields=[
                ('fleet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.fleet')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('app.fleet',),
        ),
        migrations.RenameModel(
            old_name='UberFleet',
            new_name='UberRequest',
        ),
        migrations.RemoveField(
            model_name='boltpaymentsorder',
            name='partner',
        ),
        migrations.DeleteModel(
            name='BoltTransactions',
        ),
        migrations.DeleteModel(
            name='FileNameProcessed',
        ),
        migrations.RemoveField(
            model_name='newuklonpaymentsorder',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='uberpaymentsorder',
            name='partner',
        ),
        migrations.DeleteModel(
            name='UberTransactions',
        ),
        migrations.DeleteModel(
            name='WeeklyReportFile',
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers', verbose_name='Фото водія'),
        ),
        migrations.AddField(
            model_name='fleet',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.partner', verbose_name='Партнери'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(null=True, verbose_name='Дата початку роботи'),
        ),
        migrations.RenameModel(
            old_name='BoltFleet',
            new_name='BoltRequest',
        ),
        migrations.DeleteModel(
            name='BoltPaymentsOrder',
        ),
        migrations.RenameModel(
            old_name='NewUklonFleet',
            new_name='UklonRequest',
        ),
        migrations.DeleteModel(
            name='NewUklonPaymentsOrder',
        ),
        migrations.DeleteModel(
            name='UberPaymentsOrder',
        ),
    ]
