# Generated by Django 4.1 on 2023-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_boltrequest_uagpssynchronizer_uklonrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uklonrequest',
            name='token',
        ),
        migrations.AddField(
            model_name='boltrequest',
            name='base_url',
            field=models.URLField(default='https://fleetownerportal.live.boltsvc.net/fleetOwnerPortal/'),
        ),
        migrations.AddField(
            model_name='uagpssynchronizer',
            name='base_url',
            field=models.URLField(default='https://gps.overseer.ua/'),
        ),
        migrations.AddField(
            model_name='uberrequest',
            name='base_url',
            field=models.URLField(default='https://supplier.uber.com/graphql'),
        ),
        migrations.AddField(
            model_name='uklonrequest',
            name='base_url',
            field=models.URLField(default='https://fleets.uklon.com.ua/api/'),
        ),
    ]
