# Generated by Django 4.1 on 2023-11-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_remove_uklonrequest_token_boltrequest_base_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('gps_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='gps_id',
        ),
        migrations.AlterField(
            model_name='uagpssynchronizer',
            name='base_url',
            field=models.URLField(default='https://uagps.net/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gpsnumber', verbose_name='Назва авто в Gps'),
        ),
    ]
