# Generated by Django 4.1 on 2023-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_gpsnumber_remove_vehicle_gps_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uagpssynchronizer',
            name='base_url',
        ),
        migrations.AddField(
            model_name='partner',
            name='gps_url',
            field=models.URLField(null=True, verbose_name='Сторінка логіну Gps'),
        ),
    ]
