# Generated by Django 4.1 on 2023-11-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_uagpssynchronizer_base_url_partner_gps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gpsnumber', verbose_name='Назва авто в Gps'),
        ),
    ]
